services:
  scheduler:
    volumes:
      - ./data:/usr/local/airflow/data
  webserver:
    volumes:
      - ./data:/usr/local/airflow/data
  triggerer:
    volumes:
      - ./data:/usr/local/airflow/data